# Generated by Django 2.2.16 on 2020-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expenses',
            field=models.IntegerField(default=1, verbose_name='経費'),
        ),
        migrations.AddField(
            model_name='project',
            name='expenses_item',
            field=models.CharField(default=1, max_length=500, verbose_name='経費項目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=500, verbose_name='プロジェクト名'),
        ),
    ]
