# Generated by Django 2.2.16 on 2020-10-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('goal_name', models.CharField(max_length=200, verbose_name='試験名')),
                ('due_date', models.DateField(verbose_name='試験日')),
                ('description', models.TextField(verbose_name='目標概要')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
