# Generated by Django 2.2.16 on 2020-10-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_auto_20201025_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=200, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=200, verbose_name='パスワード')),
            ],
        ),
    ]
