# Generated by Django 2.2.16 on 2020-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_auto_20201123_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expenses',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='経費'),
        ),
        migrations.AlterField(
            model_name='project',
            name='expenses_item',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='経費項目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='プロジェクト名'),
        ),
    ]
