# Generated by Django 2.2.16 on 2020-10-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_signin_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
