# Generated by Django 2.2.16 on 2020-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_auto_20201123_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expenses',
            field=models.CharField(blank=True, max_length=200, verbose_name='経費'),
        ),
        migrations.AlterField(
            model_name='project',
            name='expenses_item',
            field=models.CharField(blank=True, max_length=200, verbose_name='経費項目'),
        ),
    ]
