# Generated by Django 2.2.16 on 2020-11-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_auto_20201128_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
    ]
