# Generated by Django 2.2.16 on 2020-11-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_signin_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='goal_name',
        ),
    ]
