# Generated by Django 2.2.16 on 2020-12-14 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0006_auto_20201129_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sum_time', models.DateField()),
                ('points', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 15, 0, 8, 28, 632938), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='設定日'),
        ),
    ]
