# Generated by Django 2.2.16 on 2020-11-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0006_remove_project_goal_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
