# Generated by Django 2.2.16 on 2020-12-26 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_auto_20201215_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyDate', models.DateField(verbose_name='勉強日')),
                ('StudyTime', models.DateField(verbose_name='勉強時間')),
                ('SelfAssesment', models.TextField(verbose_name='自己評価')),
                ('Comment', models.TextField(verbose_name='コメント')),
            ],
        ),
        migrations.DeleteModel(
            name='Project_detail',
        ),
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 26, 21, 16, 39, 663495), verbose_name='作成日'),
        ),
    ]
