# Generated by Django 2.2.16 on 2020-11-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_auto_20201108_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='due_date',
        ),
    ]
