# Generated by Django 2.2.16 on 2020-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0008_remove_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='目標'),
        ),
    ]
