# Generated by Django 2.2.16 on 2021-02-14 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0009_auto_20201226_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateField(choices=[('', ''), ('1', 15), ('2', 25), ('3', 50)], default=None, verbose_name='分')),
                ('count', models.DateField(verbose_name='セット回数')),
                ('sumtime', models.DateField(verbose_name='総勉強時間')),
                ('SelfAssesment', models.TextField(verbose_name='自己評価')),
                ('Comment', models.TextField(verbose_name='コメント')),
            ],
        ),
        migrations.DeleteModel(
            name='StudySet',
        ),
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 14, 22, 35, 51, 314680), verbose_name='作成日'),
        ),
    ]
