# Generated by Django 2.2.16 on 2021-03-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0011_auto_20210308_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 8, 23, 4, 9, 929618), verbose_name='作成日'),
        ),
    ]
