# Generated by Django 2.2.16 on 2020-11-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0012_auto_20201121_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
