# Generated by Django 2.2.16 on 2021-03-08 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0012_auto_20210308_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 8, 23, 20, 24, 253841), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='minute',
            field=models.IntegerField(choices=[('', 'minute'), (15, 15), (25, 25), (50, 50)], default=None, verbose_name='分'),
        ),
    ]
