# Generated by Django 2.2.16 on 2021-03-08 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0013_auto_20210308_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 8, 23, 21, 53, 729917), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='sets',
            field=models.IntegerField(choices=[('', 'sets'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, verbose_name='セット回数'),
        ),
    ]
