# Generated by Django 2.2.16 on 2021-03-09 14:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0014_auto_20210308_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 9, 23, 27, 35, 780414), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='minute',
            field=models.CharField(choices=[('', 'minute'), ('1', 15), ('2', 25), ('3', 50)], default=django.utils.timezone.now, max_length=200, verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='sets',
            field=models.CharField(choices=[('', 'sets'), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=django.utils.timezone.now, max_length=200, verbose_name='セット回数'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='total',
            field=models.CharField(max_length=200, verbose_name='総勉強時間'),
        ),
    ]
