# Generated by Django 2.2.16 on 2021-03-10 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0015_auto_20210309_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 11, 0, 9, 5, 553509), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='minute',
            field=models.CharField(default='0', max_length=200, verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='sets',
            field=models.CharField(default='0', max_length=200, verbose_name='セット回数'),
        ),
    ]
