# Generated by Django 2.2.16 on 2021-03-11 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0016_auto_20210311_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 11, 22, 21, 28, 237978), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='minute',
            field=models.IntegerField(choices=[('1', 15), ('2', 25), ('3', 50)], verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='sets',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], verbose_name='セット回数'),
        ),
        migrations.AlterField(
            model_name='setplan',
            name='total',
            field=models.IntegerField(verbose_name='総勉強時間'),
        ),
    ]
