# Generated by Django 2.2.16 on 2021-03-11 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0018_auto_20210311_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 11, 22, 23, 13, 730431), verbose_name='作成日'),
        ),
    ]
